// Lightweight Nigeria locations dataset for state and city/LGA dropdowns
// This is not an exhaustive list of every city, but covers common locations

export const NIGERIA_STATES: string[] = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
  'FCT Abuja',
];

export const NIGERIA_CITIES_BY_STATE: Record<string, string[]> = {
  'Abia': ['Umuahia', 'Aba', 'Ohafia'],
  'Adamawa': ['Yola', 'Mubi', 'Jimeta'],
  'Akwa Ibom': ['Uyo', 'Ikot Ekpene', 'Eket'],
  'Anambra': ['Awka', 'Onitsha', 'Nnewi'],
  'Bauchi': ['Bauchi', 'Azare', 'Misau'],
  'Bayelsa': ['Yenagoa', 'Brass', 'Ogbia'],
  'Benue': ['Makurdi', 'Gboko', 'Otukpo'],
  'Borno': ['Maiduguri', 'Biu', 'Bama'],
  'Cross River': ['Calabar', 'Ikom', 'Ogoja'],
  'Delta': ['Asaba', 'Warri', 'Sapele', 'Ughelli'],
  'Ebonyi': ['Abakaliki', 'Afikpo'],
  'Edo': ['Benin City', 'Auchi', 'Ekpoma'],
  'Ekiti': ['Ado Ekiti', 'Ikere Ekiti'],
  'Enugu': ['Enugu', 'Nsukka', 'Awgu'],
  'Gombe': ['Gombe', 'Kaltungo'],
  'Imo': ['Owerri', 'Orlu', 'Okigwe'],
  'Jigawa': ['Dutse', 'Hadejia'],
  'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan'],
  'Kano': ['Kano', 'Wudil'],
  'Katsina': ['Katsina', 'Daura', 'Funtua'],
  'Kebbi': ['Birnin Kebbi', 'Argungu'],
  'Kogi': ['Lokoja', 'Okene', 'Idah'],
  'Kwara': ['Ilorin', 'Offa'],
  'Lagos': ['Ikeja', 'Lagos Island', 'Surulere', 'Lekki', 'Ikorodu'],
  'Nasarawa': ['Lafia', 'Keffi'],
  'Niger': ['Minna', 'Bida', 'Suleja'],
  'Ogun': ['Abeokuta', 'Ijebu Ode', 'Sagamu'],
  'Ondo': ['Akure', 'Ondo', 'Owo'],
  'Osun': ['Osogbo', 'Ife', 'Ilesa'],
  'Oyo': ['Ibadan', 'Ogbomoso', 'Oyo'],
  'Plateau': ['Jos', 'Bukuru'],
  'Rivers': ['Port Harcourt', 'Bonny', 'Omoku'],
  'Sokoto': ['Sokoto'],
  'Taraba': ['Jalingo', 'Wukari'],
  'Yobe': ['Damaturu', 'Potiskum'],
  'Zamfara': ['Gusau', 'Kaura Namoda'],
  'FCT Abuja': ['Abuja', 'Gwagwalada', 'Kuje'],
};


